name: run-test-on-pull-request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  call-test-on-pull-request:
  uses: ./.github/workflows/reusable-workflow.yml
  with:
    tag-for-test-to-run:"smoke"
  secrets: inherit

