name: run-test-on-pull-request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  call-test-on-pull-request: ./.github/workflows/reusable-workflow.yml
  uses: organization/repo/.github/workflows/build-test-deploy.yml@main
  with:
    tag-for-test-to-run:"smoke"
  secrets: inherit

