name: reusable-workflow-to-build-test-deploy
# Changed 'on' to enable this workflow to be called from other workflows
on:
  workflow_call:
    # Introduced 'inputs' to define parameters that can be passed when calling this workflow
    inputs:
      tag-for-test-to-run:
        required: true
        type: string
      tag-for-test-to-exclude:
        required: false
        type: string
        default: "flaky,failing"
      test-environment:
        required: false
        type: string
        default: "STAGING"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Build with Maven
        run: mvn
          -DexcludedGroups="${{ inputs.tag-for-test-to-exclude }}"
          -Dgroups="${{ inputs.tag-for-test-to-run }}"
          -DTEST_ENV="{{inputs.test-environment}}"
          -B package --file pom.xml
